name: Check frontend code lint
on: 
  pull_request:
    paths:
      - 'web-app/client/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set Node.js
          uses: actions/setup-node@v4
          with:
            node-version-file: 'web-app/client/.nvmrc'

        - name: Install server dependencies
          working-directory: web-app/server
          run: yarn install --immutable

        - name: Generate server schema
          working-directory: web-app/server
          run: yarn generate
        
        - name: Install client dependencies
          working-directory: web-app/client
          run: yarn install --immutable

        - name: Generate client types
          working-directory: web-app/client
          run: |
            yarn codegen:server
            yarn codegen:cms
        
        - name: Run lint
          working-directory: web-app/client
          run: yarn lint

